version: '3.11'
services:
    web:
        build: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
        ports:
           - 8000:8000
        env_file: 
            - .env
        restart: "on-failure"