# Generated by Django 4.2.2 on 2023-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0, verbose_name='طول جغرافیایی')),
                ('latitude', models.FloatField(default=0, verbose_name='عرض جغرافیایی')),
                ('free', models.BooleanField(default=True, help_text='درحال انجام ماموریت یا آزاد', verbose_name='آزاد')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'راننده ها',
            },
        ),
    ]
