# Generated by Django 4.2.2 on 2023-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='free',
            field=models.BooleanField(default=True, help_text='درحال انجام ماموریت یا آزاد', verbose_name='آزاد'),
        ),
    ]
