# Generated by Django 4.2.2 on 2023-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='طول جغرافیایی'),
        ),
    ]
