# Generated by Django 4.2.2 on 2023-06-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('origin_longitude', models.FloatField(default=0, verbose_name='طول جغرافیایی مبدا')),
                ('origin_latitude', models.FloatField(default=0, verbose_name='عرض جغرافیایی مبدا')),
                ('destination_longitude', models.FloatField(default=0, verbose_name='طول جغرافیایی مقصد')),
                ('destination_latitude', models.FloatField(default=0, verbose_name='عرض جغرافیایی مقصد')),
                ('done', models.BooleanField(default=False, help_text='درحال انجام یا انجام شده', verbose_name='انجام شده')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'ماموریت',
                'verbose_name_plural': 'ماموریت ها',
            },
        ),
    ]
