# Generated by Django 4.2.2 on 2023-06-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False, help_text='درحال انجام یا انجام شده', verbose_name='انجام شده')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'ماموریت',
                'verbose_name_plural': 'ماموریت ها',
            },
        ),
    ]
