# Generated by Django 4.2.2 on 2023-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
