# Generated by Django 4.2.2 on 2023-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destination_latitude',
            field=models.FloatField(default=0, verbose_name='عرض جغرافیایی مقصد'),
        ),
        migrations.AddField(
            model_name='mission',
            name='destination_longitude',
            field=models.FloatField(default=0, verbose_name='طول جغرافیایی مقصد'),
        ),
        migrations.AddField(
            model_name='mission',
            name='origin_latitude',
            field=models.FloatField(default=0, verbose_name='عرض جغرافیایی مبدا'),
        ),
        migrations.AddField(
            model_name='mission',
            name='origin_longitude',
            field=models.FloatField(default=0, verbose_name='طول جغرافیایی مبدا'),
        ),
    ]
